#!/usr/bin/env zsh

_source_named_configs() {
    local name file
    for name in "$@"; do
        file="$ZDOTDIR/$name"
        [[ -f "$file" ]] && source "$file"
        for file in "$XDG_CONFIG_HOME"/*/"$name"(N); do
            [[ "${file:h:t}" == zsh ]] && continue
            source "$file"
        done
    done
}

_source_named_configs env.zsh path.zsh
unfunction _source_named_configs
